#!/usr/bin/env python3
"""Exact certificate: deferred readouts on both networks of PR104's stopped product-ring interchange.

Inputs (regenerated by the two scripts in this directory):
  bit-profile.json      Swapnil Jain's round-seven deferred bit word, one child per residual (bit_round7.py);
  complex-profile.json  PR104's h=24 complex network with lifted binary frames and deferred readouts
                        (complex_deferred.py).
Computes, with PR104's inherited exact routines: the largest coarse bit saving and complex saving on the
10^-10 grid with a contracting moment, the stopped ordinary bit saving (PR104 stopping at theta = 1/1000),
the finite semantic/product-row bridge (row stock raised as the larger children require; it enters only the
row slack and cutoffs) and the 47-constraint balanced assembly at the largest kappa on the 10^-10 grid.
Usage: python3 research/deferred-stopped/certificate.py      (writes certificate.json)
Prepared by Avi Eisenberg (ikeboy) with Anthropic Claude assistance. Apache-2.0.
"""
import json
import sys
from fractions import Fraction as Q
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from partial_swap_network import moment                                    # noqa: E402
from copied_centers_network import finite_bridge as copied_bridge          # noqa: E402
from structured_bulk_assembly import assembly, js                          # noqa: E402

GRID = 10**10
ATOM = Q(1, 1000)                       # PR104 stopping exponent theta
OLD = Q(384599, 10**10)                 # PR104 retained ordinary leaf saving
PHASE_STOP = Q(1, 10**6)                # PR104 beta


def require(ok, msg):
    if not ok:
        raise SystemExit('FAIL: ' + msg)


def profile(name):
    p = json.loads((HERE / name).read_text())
    p['child_multiplicities'] = {int(t): c for t, c in p['child_multiplicities'].items()}
    z = p['child_multiplicities']
    require(sum(t * c for t, c in z.items()) == p['total_rank'] == p['W'] * p['m'] - p['N'] + p['L'], name + ' rank mass')
    require(all(0 < t < p['m'] and c > 0 for t, c in z.items()), name + ' children')
    require(max(z) == p['maxchild'], name + ' maxchild')
    return p


def contracts(p, a):
    try:
        moment(p['m'], p['W'], p['child_multiplicities'], a, True)
        return True
    except SystemExit:
        return False
    except Exception:
        return False


def largest(p, lo, hi):
    a, b = int(lo * GRID), int(hi * GRID)
    require(contracts(p, Q(a, GRID)) and not contracts(p, Q(b, GRID)), 'bracket')
    while b - a > 1:
        mid = (a + b) // 2
        a, b = (mid, b) if contracts(p, Q(mid, GRID)) else (a, mid)
    return Q(a, GRID)


def main():
    bit, phase = profile('bit-profile.json'), profile('complex-profile.json')
    coarse = largest(bit, Q(7, 10**5), Q(2, 10**4))
    ac = largest(phase, Q(7, 10**5), Q(2, 10**4))
    bm = moment(bit['m'], bit['W'], bit['child_multiplicities'], coarse, True)
    cm = moment(phase['m'], phase['W'], phase['child_multiplicities'], ac, True)
    require(not contracts(bit, coarse + Q(1, GRID)) and not contracts(phase, ac + Q(1, GRID)), 'next grid points rejected')
    require(0 < OLD <= coarse < ATOM < 1, 'stopped-adapter exponents')
    ab = (1 - ATOM) * coarse + ATOM * OLD
    require(ATOM > ab, 'adapter toll subordinate to the stopped saving')
    abit = min(ab, (1 - PHASE_STOP) * ac - Q(1, GRID))

    row = dict(h=phase['h'], v=phase['v'], c=phase['additions'], central_disjoint=24)
    previous = json.loads((ROOT / 'certificates' / 'copied-centers-network.json').read_text())
    bridge = copied_bridge(bit, phase, [row, row])
    old_bit = previous['finite_bridge']['bit']
    old_degree = old_bit['halving_degree'] * old_bit['wire_bits']
    require(old_degree == 252, 'inherited ordinary leaf row stock')
    coarse_bridge = bridge.pop('bit'); cpx = bridge['complex']
    coefficient = (coarse_bridge['halving_degree'] * coarse_bridge['wire_bits'] + old_degree +
                   cpx['halving_degree'] * cpx['wire_bits'])
    degree = 1000 * ((51 * coefficient) // 25000 + 1)
    require(Q(degree) > Q(51 * coefficient, 25), 'product stock strictly sufficient')
    bridge.update(bit_coarse=coarse_bridge, ordinary_leaf_row_degree=old_degree)
    bridge['rows'] = dict(coefficient=coefficient, degree=degree, suffix_slope=4 * degree,
                          degree_gap=Q(degree) - Q(51 * coefficient, 25),
                          contract='W_complex^D_complex * W_coarse^D_coarse * W_old^D_old; one preceding prefix and one padding; sequential reuse')
    bridge['semantic'].update(fixed_odd_divisor=21,
                              exact_grid='One common dyadic grid times the fixed odd divisor to K=G*(D_complex+1); no child rounding')

    def accepted(k):
        try:
            assembly(abit, ac, bridge, Q(k, GRID), beta=PHASE_STOP)
            return True
        except AssertionError:
            return False
    lo, hi = int(Q(7, 10**5) * GRID), int(ac * GRID) + 1
    require(accepted(lo) and not accepted(hi), 'kappa bracket')
    while hi - lo > 1:
        mid = (lo + hi) // 2
        lo, hi = (mid, hi) if accepted(mid) else (lo, mid)
    kappa = Q(lo, GRID)
    assembled = assembly(abit, ac, bridge, kappa, beta=PHASE_STOP)
    require(not accepted(lo + 1), 'next kappa grid point rejected')
    require(len(assembled['strict_constraints']) == 47 and len(assembled['margins']) == 7, 'complete assembly')
    assembled['parameters']['actual_bit_saving'] = ab
    result = dict(status='Conditional witness: deferred readouts on both networks of the stopped product-ring interchange',
                  kappa=kappa, bit=dict(coarse_saving=coarse, stopped_saving=ab, moment_gap=bm['strict_gap'],
                                        counts={k: bit[k] for k in ('h', 'v', 'R', 'm', 'W', 'total_rank', 'maxchild', 'deferred_slots')}),
                  complex=dict(saving=ac, moment_gap=cm['strict_gap'],
                               counts={k: phase[k] for k in ('h', 'v', 'R', 'm', 'W', 'total_rank', 'maxchild', 'deferred_roles')}),
                  finite_bridge=bridge, assembly=assembled,
                  base='PR104 head 854ba7dca98651eab2050402384e1a7784534f0a')
    (HERE / 'certificate.json').write_text(json.dumps(js(result), indent=2, sort_keys=True) + '\n')
    print('PASS kappa = %s = %.10e' % (kappa, float(kappa)))
    print('coarse bit saving %s, stopped %s, complex saving %s' % (coarse, ab, ac))


if __name__ == '__main__':
    main()
